project_id = "csmegxwehniyfvbbjqbz"

[functions.get-realtime-token]
verify_jwt = false

[functions.chat-with-iasted]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false
